services:
  app:
    build:
      context: .
      dockerfile: .docker/php/Dockerfile
    container_name: metal-app
    volumes:
      - ./:/var/www/html
    depends_on:
      - postgres

  nginx:
    image: nginx:stable
    container_name: metal-nginx
    ports:
      - "8000:80"
    volumes:
      - ./:/var/www/html
      - ./.docker/nginx:/etc/nginx/conf.d
    depends_on:
      - app

  postgres:
    image: postgres:15
    container_name: metal-postgres
    ports:
      - "5436:5432"
    environment:
      POSTGRES_DB: ${DB_DATABASE}
      POSTGRES_USER: ${DB_USERNAME}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
    volumes:
      - pg_data:/var/lib/postgresql/data

volumes:
  pg_data:
